### ISSUE TITLE
TypeError: init() got an unexpected keyword argument 'skip_link_detection'

### ISSUE THREAD

**Issue by ntoll** [adafruit/Adafruit_Board_Toolkit#3]
For context and log file please see: https://github.com/mu-editor/crash-reports/issues/117

Mu user @Ardo9602 reports:

> Adafruit RP2040 with Circuitpython 6.2.0 beta4 and release
> Microbit with Micropython
>
> Editor starts fine with no board connected, crashes with any of these connected, connecting before or after program start makes no difference. 

Stack trace from Mu logs (provided by user)

```
2021-05-01 23:04:35,139 - root:173(excepthook) ERROR: Unrecoverable error
Traceback (most recent call last):
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\logic.py", line 711, in check_usb
detected = mode.find_devices(with_logging=False)
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\base.py", line 423, in find_devices
device = self.compatible_board(port)
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\mu\modes\circuitpython.py", line 286, in compatible_board
for comport in circuitpython_serial.repl_comports():
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\adafruit_board_toolkit\circuitpython_serial.py", line 61, in repl_comports
port for port in comports() if port.interface.startswith("CircuitPython CDC ")
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\adafruit_board_toolkit\circuitpython_serial.py", line 46, in comports
ports = _list_ports_windows.comports()
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\adafruit_board_toolkit_list_ports_windows.py", line 458, in comports
return list(iterate_comports())
File "C:\Users\Admiq\AppData\Local\Programs\Mu Editor\Python\lib\site-packages\adafruit_board_toolkit_list_ports_windows.py", line 342, in iterate_comports
info = list_ports_common.ListPortInfo(port_name_buffer.value, skip_link_detection=True)
TypeError: init() got an unexpected keyword argument 'skip_link_detection'
```

**Comment by ntoll** [comment]
Apologies @dhalbert - I missed your comment on the Mu issue. Closing this because it seems to be a PySerial / local user packaging problem.
